sonar.projectKey=Firefox2100_roleplay-catalogue
sonar.organization=firefox2100
sonar.projectName=Roleplay Catalogue
sonar.sources=src,frontend/src
sonar.tests=tests,frontend/src
sonar.exclusions=frontend/src/**/*.test.js,frontend/src/**/*.test.jsx,frontend/src/test/**
sonar.test.inclusions=tests/**/*.py,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx,frontend/src/test/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.testExecutionReportPaths=frontend/test-results-sonar.xml
sonar.sourceEncoding=UTF-8
