sonar.projectKey=Firefox2100_roleplay-catalogue
sonar.organization=firefox2100
sonar.projectName=Roleplay Catalogue
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
