storage:
  dbPath: /data/db
net:
  port: 27017
  bindIpAll: true
replication:
  replSetName: rs0
setParameter:
  searchIndexManagementHostAndPort: mongodb-search:27028
  mongotHost: mongodb-search:27028
  skipAuthenticationToSearchIndexManagementServer: true
  useGrpcForSearch: true
  searchTLSMode: disabled
